name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to ec2 server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: "${{ secrets.REMOTE_TARGET }}"
        EXCLUDE: "/dist/, /node_modules/, .git/"
        SCRIPT_BEFORE: |
          whoami
          ls -al
        SCRIPT_AFTER: |
          sudo  rsync -rtuv ~/shiftcode /home/wwwroot/www.shiftcoder.com/wp-content/themes 
          sudo chown -R www:www /home/wwwroot/www.shiftcoder.com/wp-content/themes/shiftcoder
          whoami